#!/usr/bin/env node
// P5-90 (accordproject/concerto-rust#436), Phase 0, measure only: the
// tables of the P5-90 results, from the files p590-run.sh and p590-dhat.mjs
// wrote. Prints Markdown.
//
//   node migration/bench/p590-tables.mjs [results dir] > <results dir>/tables.md
//
// Timed figures are the median of the three rounds' medians (us per item).

import fs from 'fs';
import path from 'path';

const R = process.argv[2] || 'migration/bench/results/P5-90';
const OPS = ['modelfile_new', 'add_model_file', 'add_cto_model', 'extract_cold'];
const SETS = ['concerto-core-test-data', 'conformance', 'synthetic-large'];
const BUCKETS = ['wasm', 'cto-parse', 'stringify', 'utf8-encode', 'call-copy', 'parse', 'views', 'weak', 'gc', 'ts-core', 'other'];
const rd = (f) => JSON.parse(fs.readFileSync(path.join(R, f), 'utf8'));
const med = (a) => { const s = [...a].sort((x, y) => x - y); const n = s.length; return n % 2 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2; };
const us = (v) => (v >= 1000 ? `${(v / 1000).toFixed(2)} ms` : `${v.toFixed(1)} us`);
const pct = (v) => (v === undefined ? '-' : `${v.toFixed(1)}%`);
const out = [];
const p = (s = '') => out.push(s);

function timed(side, op, set) {
    const v = [];
    for (const r of [1, 2, 3]) {
        const f = `timed/${side}-${r}-${op}.json`;
        if (!fs.existsSync(path.join(R, f))) { continue; }
        const x = rd(f).results.find((e) => e.op === op && e.set === set);
        if (x) { v.push(x.medianUs); }
    }
    return v;
}

p('# P5-90 Phase 0: model loading and extract_cold profile');
p();
p('Measure only (accordproject/concerto-rust#436). Generated by `p590-tables.mjs` from this directory.');
p();
p('## TS API (Rust engine) against TS 5.0.0, same run');
p();
p('Median of three round medians, one op per process, behind the quiet gate (300 samples, extract_cold 30).');
p();
p('| op | set | TS 5.0.0 | TS API (Rust) | x TS | rounds TS | rounds Rust |');
p('|---|---|---:|---:|---:|---|---|');
for (const op of OPS) {
    for (const set of SETS) {
        const t = timed('ts', op, set);
        const r = timed('rust', op, set);
        if (!t.length || !r.length) { continue; }
        p(`| ${op} | ${set} | ${us(med(t))} | ${us(med(r))} | ${(med(r) / med(t)).toFixed(2)} | ${t.map((x) => x.toFixed(1)).join(' / ')} | ${r.map((x) => x.toFixed(1)).join(' / ')} |`);
    }
}
p();
p('## Wall-time split (V8 CPU profile, named dlmalloc engine)');
p();
p('Share of profiled wall time per bucket (`p590-split.mjs`). wasm alloc is the allocator part of wasm (dlmalloc, memcpy/memset, Vec growth).');
p();
p(`| op | set | ${BUCKETS.join(' | ')} | wasm alloc |`);
p(`|---|---|${BUCKETS.map(() => '---:').join('|')}|---:|`);
const split = (eng, op, set) => {
    const f = `cpuprof/${eng}-${op}-${set}.split.json`;
    return fs.existsSync(path.join(R, f)) ? rd(f) : null;
};
const allocShare = (j) => j.detail.filter((d) => / alloc( |$)/.test(d[0]) && d[0].startsWith('wasm')).reduce((a, d) => a + d[1], 0);
for (const op of OPS) {
    for (const set of SETS) {
        const j = split('dlmalloc', op, set);
        if (!j) { continue; }
        p(`| ${op} | ${set} | ${BUCKETS.map((b) => pct(j.buckets[b])).join(' | ')} | ${pct(allocShare(j))} |`);
    }
}
p();
p('### WASM time by binding and stage');
p();
p('| op | set | wasm part | share |');
p('|---|---|---|---:|');
for (const op of OPS) {
    for (const set of SETS) {
        const j = split('dlmalloc', op, set);
        if (!j) { continue; }
        const t = {};
        for (const [k, v] of j.detail) {
            if (!k.startsWith('wasm ')) { continue; }
            const s = k.includes(' | ') ? k.split(' | ')[1] : k.slice(5);
            t[s] = (t[s] || 0) + v;
        }
        for (const [k, v] of Object.entries(t).sort((a, b) => b[1] - a[1]).filter(([, v]) => v >= 0.5)) {
            p(`| ${op} | ${set} | ${k} | ${pct(v)} |`);
        }
    }
}
p();
p('## Engine call counts (count mode, one run per engine)');
p();
p('| engine | op | set | wall us/item | crossings/item | in-engine us/item (share) |');
p('|---|---|---|---:|---:|---:|');
for (const eng of ['dlmalloc', 'talc']) {
    const f = `count/${eng}.log`;
    if (!fs.existsSync(path.join(R, f))) { continue; }
    for (const l of fs.readFileSync(path.join(R, f), 'utf8').split('\n')) {
        const m = /^(\S+)\s+(\S+)\s+n=\s*\d+ wall\s+([\d.]+) us\/item\s+crossings\s+([\d.]+)\/item\s+in-engine\s+([\d.]+) us \((\d+)%\)/.exec(l);
        if (m) { p(`| ${eng} | ${m[1]} | ${m[2]} | ${m[3]} | ${m[4]} | ${m[5]} (${m[6]}%) |`); }
    }
}
p();
p('## Typed read alone: WASM (dlmalloc, throwaway talc) against native');
p();
p('stageModelFileCheckedUtf8 straight on the engine module (`p590-typedread.mjs`), and the native `ModelFile::from_json_text_checked_with_imports` (`p590_typed_read time`). us per file, median of three rounds.');
p();
p('| set | native | WASM dlmalloc stage | drop | WASM talc stage | drop | dlmalloc / native | talc / dlmalloc (stage) |');
p('|---|---:|---:|---:|---:|---:|---:|---:|');
for (const set of SETS) {
    const tr = (al, k) => med([1, 2, 3].map((r) => rd(`timed/typedread-${al}-${r}.json`).results.find((e) => e.set === set)[k]));
    const nat = med([1, 2, 3].map((r) => Number(fs.readFileSync(path.join(R, `timed/native-${r}.tsv`), 'utf8').split('\n').find((l) => l.split('\t')[1] === set).split('\t')[2])));
    const ds = tr('dlmalloc', 'stageUs');
    const ts = tr('talc', 'stageUs');
    p(`| ${set} | ${nat.toFixed(2)} | ${ds.toFixed(2)} | ${tr('dlmalloc', 'dropUs').toFixed(2)} | ${ts.toFixed(2)} | ${tr('talc', 'dropUs').toFixed(2)} | ${(ds / nat).toFixed(2)} | ${(ts / ds).toFixed(2)} |`);
}
p();
p('## WeakMap stall (P5-73) re-measured');
p();
p('mm_new, modelfile_new and add_model_file in one process against one process per op (600 samples), median us per item.');
p();
p('| op | set | one process r1 | r2 | alone r1 | r2 | probe, one process | probe, alone |');
p('|---|---|---:|---:|---:|---:|---:|---:|');
const wk = (f, op, set) => { const x = rd(`weak/${f}`).results.find((e) => e.op === op && e.set === set); return x ? x.medianUs.toFixed(1) : '-'; };
for (const op of ['mm_new', 'modelfile_new', 'add_model_file']) {
    for (const set of SETS) {
        if (wk('one-process-1.json', op, set) === '-') { continue; }
        p(`| ${op} | ${set} | ${wk('one-process-1.json', op, set)} | ${wk('one-process-2.json', op, set)} | ${wk(`alone-1-${op}.json`, op, set)} | ${wk(`alone-2-${op}.json`, op, set)} | ${wk('probe-one-process-sweep.json', op, set)} | ${wk(`probe-alone-${op}-sweep.json`, op, set)} |`);
    }
}
p();
p('Probe (`p590-weak-probe.cjs`), weak-collection ops by creation site; the probe adds two clock reads per call.');
p();
p('| run | site and op | calls | us/call | max us | calls > 20 us | calls > 100 us |');
p('|---|---|---:|---:|---:|---:|---:|');
for (const run of ['one-process', 'alone-modelfile_new', 'alone-add_model_file']) {
    for (const e of rd(`weak/probe-${run}.json`).slice(0, 5)) {
        p(`| ${run} | ${e.key} | ${e.calls} | ${(e.totalUs / e.calls).toFixed(2)} | ${e.maxUs.toFixed(0)} | ${e.over20us} | ${e.over100us} |`);
    }
}
p();
p('## Native allocation profile of the typed read');
p();
p('`p590_typed_read alloc` (counting allocator) and `valgrind --tool=dhat` on `p590_typed_read loop` (`p590-dhat.mjs`), per file read.');
p();
p('| set | allocs | reallocs | bytes | input bytes |');
p('|---|---:|---:|---:|---:|');
for (const l of fs.readFileSync(path.join(R, 'timed/native-alloc.tsv'), 'utf8').split('\n').filter(Boolean)) {
    const c = l.split('\t');
    p(`| ${c[1]} | ${c[2].split(' ')[1]} | ${c[3].split(' ')[1]} | ${c[4].split(' ')[1]} | ${c[5].split(' ')[2]} |`);
}
for (const set of SETS) {
    const f = `dhat/${set}.json`;
    if (!fs.existsSync(path.join(R, f))) { continue; }
    const j = rd(f);
    p();
    p(`### ${set}: ${j.blocksPerLoad.toFixed(1)} allocations, ${Math.round(j.bytesPerLoad)} bytes per file`);
    p();
    p('| by kind | allocs/file | bytes/file |');
    p('|---|---:|---:|');
    for (const k of j.kinds.filter((k) => k.blocksPerLoad > 0)) { p(`| ${k.key} | ${k.blocksPerLoad} | ${k.bytesPerLoad} |`); }
    p();
    p('| by origin (top 10) | allocs/file | bytes/file |');
    p('|---|---:|---:|');
    for (const k of j.origins.slice(0, 10)) { p(`| ${k.key} | ${k.blocksPerLoad} | ${k.bytesPerLoad} |`); }
}
console.log(out.join('\n'));
