#!/usr/bin/env node
// P5-91 (accordproject/concerto-rust#437): turns p591-run.sh's output into
// tables.md in the same directory. Measure only.
//
//   node migration/bench/p591-tables.mjs <out dir>

import fs from 'fs';
import path from 'path';
import { requireRawInputs } from './lib/raw-inputs.mjs';

const dir = process.argv[2];
requireRawInputs(dir);
const read = (f) => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
const median = (xs) => { const s = xs.slice().sort((a, b) => a - b); return s[Math.floor(s.length / 2)]; };
const pct = (now, before) => `${((now / before - 1) * 100).toFixed(1)}%`;
const lines = [];
const out = (s = '') => lines.push(s);

out('# P5-91: views.ts load-path bookkeeping, before and after');
out();
out('Measure only (accordproject/concerto-rust#437). Generated by `p591-tables.mjs` from `p591-run.sh` output in this directory.');
out('Before is the integration head without P5-91 (concerto 4232b7835), now is the P5-91 tree; both run the same engine build');
out('(concerto-rust 4433195, concerto-wasm `build.sh`). Machine load during the run is in `loads.txt`.');
out();

out('## Weak-collection operations per item (`--mode weak`)');
out();
out('| op | set | lookups before | now | writes before | now | inserts before | now | FinalizationRegistry.register before | now |');
out('|---|---|---:|---:|---:|---:|---:|---:|---:|---:|');
const wb = read('weak-before.json').rows;
const wn = read('weak-now.json').rows;
for (const b of wb) {
    const n = wn.find((r) => r.op === b.op && r.set === b.set);
    out(`| ${b.op} | ${b.set} | ${b.lookups.toFixed(2)} | ${n.lookups.toFixed(2)} | ${b.writes.toFixed(2)} | ${n.writes.toFixed(2)} | ${b.inserts.toFixed(2)} | ${n.inserts.toFixed(2)} | ${b.finalizerRegisters.toFixed(2)} | ${n.finalizerRegisters.toFixed(2)} |`);
}
out();

out('## JS heap bytes allocated per item (`--mode alloc`, median of 11 rounds without a collection)');
out();
out('| op | set | before | now | change |');
out('|---|---|---:|---:|---:|');
const ab = read('alloc-before.json').rows;
const an = read('alloc-now.json').rows;
for (const b of ab) {
    const n = an.find((r) => r.op === b.op && r.set === b.set);
    out(`| ${b.op} | ${b.set} | ${b.bytesPerItem.toFixed(0)} | ${n.bytesPerItem.toFixed(0)} | ${pct(n.bytesPerItem, b.bytesPerItem)} |`);
}
out();

out('## Engine crossings per item (`p515-sweep.mjs --mode count`)');
out();
out('| op | set | before | now |');
out('|---|---|---:|---:|');
const crossings = (f) => {
    const m = {};
    for (const l of fs.readFileSync(path.join(dir, f), 'utf8').split('\n')) {
        const x = /^(\S+)\s+(\S+)\s+n=.*crossings\s+([\d.]+)\/item/.exec(l);
        if (x) { m[`${x[1]} ${x[2]}`] = x[3]; }
    }
    return m;
};
const cb = crossings('count-before.log');
const cn = crossings('count-now.log');
for (const k of Object.keys(cb)) {
    const [op, set] = k.split(' ');
    out(`| ${op} | ${set} | ${cb[k]} | ${cn[k]} |`);
}
out();

out('## Timing, interleaved in one process (`--mode ab`, median us per item of 31 rounds)');
out();
out('| op | set | before | now | change |');
out('|---|---|---:|---:|---:|');
for (const r of read('ab.json').rows) {
    out(`| ${r.op} | ${r.set} | ${r.beforeUs.toFixed(2)} | ${r.nowUs.toFixed(2)} | ${pct(r.nowUs, r.beforeUs)} |`);
}
out();

out('## Timing, one process per side (`p515-sweep.mjs --mode time`, median of the round medians)');
out();
out('This local run had no quiet gate: the 8-core machine ran other workers (1-minute load 11 to 24, `loads.txt`), and the');
out('per-sample cv was 30-90%, so these per-process figures are dominated by load and are not a before/after result. The');
out('interleaved table above is the local comparison; the targeted timing is for cloud-3 or the next consolidated re-measure');
out('(`p591-run.sh` behind a quiet gate).');
out();
out('| op | set | before | now | change | rounds before (us) | rounds now (us) |');
out('|---|---|---:|---:|---:|---|---|');
const rounds = { before: {}, now: {} };
for (const f of fs.readdirSync(dir)) {
    const m = /^time-(\d+)-(now|before)\.log$/.exec(f);
    if (!m) { continue; }
    for (const l of fs.readFileSync(path.join(dir, f), 'utf8').split('\n')) {
        const x = /^(\S+)\s+(\S+)\s+n=\s*\d+\s+([\d.]+) us\/item/.exec(l);
        if (x) { ((rounds[m[2]][`${x[1]} ${x[2]}`] ??= [])[Number(m[1]) - 1] = Number(x[3])); }
    }
}
for (const k of Object.keys(rounds.before).sort()) {
    const [op, set] = k.split(' ');
    const b = rounds.before[k];
    const n = rounds.now[k];
    out(`| ${op} | ${set} | ${median(b).toFixed(1)} | ${median(n).toFixed(1)} | ${pct(median(n), median(b))} | ${b.map((x) => x.toFixed(1)).join(' / ')} | ${n.map((x) => x.toFixed(1)).join(' / ')} |`);
}
out();
fs.writeFileSync(path.join(dir, 'tables.md'), lines.join('\n'));
process.stdout.write(lines.join('\n'));
