#!/usr/bin/env node
// P5-93 (accordproject/concerto-rust#443): the tables of the P5-93 results,
// from the files p593-run.sh wrote (and ir.tsv, below). Prints Markdown.
//
//   node migration/bench/p593-tables.mjs [results dir] > <results dir>/tables.md
//
// Timed figures are the median of the three rounds' medians (us per item).
// ir.tsv (optional): `set<TAB>before<TAB>after`, instructions per typed read
// counted by `valgrind --tool=callgrind` on `p590_typed_read loop` (the
// count for N reads less the count for none, over N x files).

import fs from 'fs';
import path from 'path';

const R = process.argv[2] || 'migration/bench/results/P5-93';
const OPS = ['modelfile_new', 'add_model_file', 'add_cto_model'];
const SETS = ['concerto-core-test-data', 'conformance', 'synthetic-large'];
const rd = (f) => JSON.parse(fs.readFileSync(path.join(R, f), 'utf8'));
const med = (a) => { const s = [...a].sort((x, y) => x - y); const n = s.length; return n % 2 ? s[(n - 1) / 2] : (s[n / 2 - 1] + s[n / 2]) / 2; };
const us = (v) => (v >= 1000 ? `${(v / 1000).toFixed(2)} ms` : `${v.toFixed(1)} us`);
const change = (b, a) => `${(((a - b) / b) * 100).toFixed(1)}%`;
const out = [];
const p = (s = '') => out.push(s);

function timed(side, op, set) {
    const v = [];
    for (const r of [1, 2, 3]) {
        const f = `timed/${side}-${r}-${op}.json`;
        if (!fs.existsSync(path.join(R, f))) { continue; }
        const x = rd(f).results.find((e) => e.op === op && e.set === set);
        if (x) { v.push(x.medianUs); }
    }
    return v;
}

function tsv(f) {
    return fs.readFileSync(path.join(R, f), 'utf8').split('\n').filter(Boolean).map((l) => l.split('\t'));
}

function alloc(side) {
    const m = {};
    for (const row of tsv(`timed/native-alloc-${side}.tsv`)) {
        const kv = {};
        for (const cell of row.slice(2)) {
            const [k, ...v] = cell.split(' ');
            kv[k === 'text' ? 'input' : k] = Number(v[v.length - 1]);
        }
        m[row[1]] = kv;
    }
    return m;
}

p('# P5-93: typed read allocation cuts, before and after');
p();
p('accordproject/concerto-rust#443, from P5-90 (#436). Generated by `p593-tables.mjs` from the files `p593-run.sh` wrote in this directory. Before: concerto-rust at the integration head the change starts from; after: the change. Same machine, same run, the order of the sides rotated every round.');
p();
p('## Native allocations per typed read');
p();
p('`p590_typed_read alloc`: heap allocations, reallocations and bytes requested per model file, counted by the example\'s global allocator, for `ModelFile::from_json_text_checked_with_imports` (what `stageModelFileChecked` runs). The WASM engine runs the same Rust code, so it makes the same allocations (the allocator differs, the requests do not).');
p();
p('| set | input bytes | allocs before | allocs after | change | reallocs before | after | bytes before | bytes after | change |');
p('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
const ab = alloc('before');
const aa = alloc('after');
for (const set of SETS) {
    const b = ab[set];
    const a = aa[set];
    p(`| ${set} | ${b.input} | ${b.allocs} | ${a.allocs} | ${change(b.allocs, a.allocs)} | ${b.reallocs} | ${a.reallocs} | ${b.bytes} | ${a.bytes} | ${change(b.bytes, a.bytes)} |`);
}
if (fs.existsSync(path.join(R, 'ir.tsv'))) {
    p();
    p('## Native instructions per typed read');
    p();
    p('`valgrind --tool=callgrind` on `p590_typed_read loop`: instructions for N reads less those for none, per file read (deterministic, unlike the timings).');
    p();
    p('| set | before | after | change |');
    p('|---|---:|---:|---:|');
    for (const [set, b, a] of tsv('ir.tsv')) {
        p(`| ${set} | ${Number(b)} | ${Number(a)} | ${change(Number(b), Number(a))} |`);
    }
}
p();
p('## Typed read alone: native and WASM');
p();
p('us per file, median of three rounds. Native: `p590_typed_read time`. WASM: `stageModelFileCheckedUtf8` straight on the engine module (`p590-typedread.mjs`, shipped dlmalloc engines), and `dropStagedModelFile` timed apart.');
p();
p('| set | native before | native after | change | WASM stage before | WASM stage after | change | drop before | drop after | WASM after / native after |');
p('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
for (const set of SETS) {
    const nat = (side) => med([1, 2, 3].map((r) => Number(tsv(`timed/native-${side}-${r}.tsv`).find((l) => l[1] === set)[2])));
    const tr = (side, k) => med([1, 2, 3].map((r) => rd(`timed/typedread-${side}-${r}.json`).results.find((e) => e.set === set)[k]));
    const [nb, na, sb, sa, db, da] = [nat('before'), nat('after'), tr('before', 'stageUs'), tr('after', 'stageUs'), tr('before', 'dropUs'), tr('after', 'dropUs')];
    p(`| ${set} | ${nb.toFixed(2)} | ${na.toFixed(2)} | ${change(nb, na)} | ${sb.toFixed(2)} | ${sa.toFixed(2)} | ${change(sb, sa)} | ${db.toFixed(2)} | ${da.toFixed(2)} | ${(sa / na).toFixed(2)} |`);
}
p();
p('## TS API ops: TS 5.0.0, and the Rust engine before and after');
p();
p('Median of three round medians, one op per process, 300 samples (30 warm-up).');
p();
p('| op | set | TS 5.0.0 | Rust before | Rust after | change | after x TS | rounds before | rounds after |');
p('|---|---|---:|---:|---:|---:|---:|---|---|');
for (const op of OPS) {
    for (const set of SETS) {
        const t = timed('ts', op, set);
        const b = timed('before', op, set);
        const a = timed('after', op, set);
        if (!t.length || !b.length || !a.length) { continue; }
        p(`| ${op} | ${set} | ${us(med(t))} | ${us(med(b))} | ${us(med(a))} | ${change(med(b), med(a))} | ${(med(a) / med(t)).toFixed(2)} | ${b.map((x) => x.toFixed(1)).join(' / ')} | ${a.map((x) => x.toFixed(1)).join(' / ')} |`);
    }
}
p();
p('## Quiet gate');
p();
const gate = fs.readFileSync(path.join(R, 'timed-loads.txt'), 'utf8').split('\n').filter((l) => / gate: /.test(l));
if (!gate.length) {
    p('Every part ran with the gate met on the first check.');
} else {
    p('Gate events from `timed-loads.txt`:');
    p();
    for (const l of gate) { p(`- ${l}`); }
}
process.stdout.write(`${out.join('\n')}\n`);
