env:
    es6: true
    node: true
    mocha: true
    jest: true
extends:
 - 'eslint:recommended'
 - 'plugin:@typescript-eslint/eslint-recommended'
 - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
 - '@typescript-eslint'
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - warn
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console: warn
    curly: error
    eqeqeq: error
    no-throw-literal: error
    strict: 0
    no-var: error
    dot-notation: error
    no-tabs: error
    no-trailing-spaces: error
    no-undef: error
    # no-use-before-define: error
    no-useless-call: error
    no-with: error
    operator-linebreak: error
    require-jsdoc: 0
    valid-jsdoc:
        - error
        - requireReturn: false
    yoda: error
