import SecurityException = require("./lib/securityexception");
import IllegalModelException = require("./lib/introspect/illegalmodelexception");
import TypeNotFoundException = require("./lib/typenotfoundexception");
import Decorator = require("./lib/introspect/decorator");
import DecoratorFactory = require("./lib/introspect/decoratorfactory");
import DecoratorManager = require("./lib/decoratormanager");
import ClassDeclaration = require("./lib/introspect/classdeclaration");
import IdentifiedDeclaration = require("./lib/introspect/identifieddeclaration");
import AssetDeclaration = require("./lib/introspect/assetdeclaration");
import ConceptDeclaration = require("./lib/introspect/conceptdeclaration");
import EnumValueDeclaration = require("./lib/introspect/enumvaluedeclaration");
import EventDeclaration = require("./lib/introspect/eventdeclaration");
import ParticipantDeclaration = require("./lib/introspect/participantdeclaration");
import TransactionDeclaration = require("./lib/introspect/transactiondeclaration");
import Property = require("./lib/introspect/property");
import Field = require("./lib/introspect/field");
import NumberValidator = require("./lib/introspect/numbervalidator");
import StringValidator = require("./lib/introspect/stringvalidator");
import EnumDeclaration = require("./lib/introspect/enumdeclaration");
import RelationshipDeclaration = require("./lib/introspect/relationshipdeclaration");
import Typed = require("./lib/model/typed");
import Identifiable = require("./lib/model/identifiable");
import Relationship = require("./lib/model/relationship");
import Resource = require("./lib/model/resource");
import Factory = require("./lib/factory");
import Globalize = require("./lib/globalize");
import Introspector = require("./lib/introspect/introspector");
import ModelFile = require("./lib/introspect/modelfile");
import ModelManager = require("./lib/modelmanager");
import Serializer = require("./lib/serializer");
import ModelUtil = require("./lib/modelutil");
import ModelLoader = require("./lib/modelloader");
import DateTimeUtil = require("./lib/datetimeutil");
import Concerto = require("./lib/concerto");
import MetaModel = require("./lib/introspect/metamodel");
/** @type {{ name: string, version: string }} */
export const version: {
    name: string;
    version: string;
};
export { SecurityException, IllegalModelException, TypeNotFoundException, Decorator, DecoratorFactory, DecoratorManager, ClassDeclaration, IdentifiedDeclaration, AssetDeclaration, ConceptDeclaration, EnumValueDeclaration, EventDeclaration, ParticipantDeclaration, TransactionDeclaration, Property, Field, NumberValidator, StringValidator, EnumDeclaration, RelationshipDeclaration, Typed, Identifiable, Relationship, Resource, Factory, Globalize, Introspector, ModelFile, ModelManager, Serializer, ModelUtil, ModelLoader, DateTimeUtil, Concerto, MetaModel };
