/* eslint-disable @typescript-eslint/no-require-imports */
/* eslint-disable no-console */
/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';

// Precompiles src/spec/concertino.schema.json into a standalone validator,
// src/spec/concertinoSchemaValidator.ts, with ajv's standalone code
// generation. The package then ships the compiled checks instead of ajv
// itself: no ajv at run time, and no `new Function`, so a strict
// Content-Security-Policy is fine.
//
//   npm run generate-validator          writes the file
//   node scripts/generateSchemaValidator.js --check
//                                       fails if the file is out of date
//
// The ajv options are the ones ConcertinoConverter used to compile the
// schema with at run time (`new Ajv()`, the defaults), so the validator
// reports the same error objects. In particular `inlineRefs` stays on:
// turning it off makes the output smaller, but changes `schemaPath` in the
// errors.

const fs = require('fs');
const path = require('path');
const Ajv = require('ajv').default;
const standaloneCode = require('ajv/dist/standalone').default;

const SCHEMA = path.resolve(__dirname, '../src/spec/concertino.schema.json');
const OUT = path.resolve(__dirname, '../src/spec/concertinoSchemaValidator.ts');

/**
 * Generates the validator module source.
 * @return {string} the TypeScript module
 */
function generate() {
    const schema = JSON.parse(fs.readFileSync(SCHEMA, 'utf8'));
    const ajv = new Ajv({ code: { source: true, esm: true } });
    const code = standaloneCode(ajv, ajv.compile(schema));
    // A schema that needs ajv's runtime helpers (ucs2length, fast-deep-equal,
    // the URI resolver) gets `require(...)` calls here. They would bring ajv
    // back as a runtime dependency, so refuse them rather than ship them.
    const requires = code.match(/require\([^)]*\)/g);
    if (requires) {
        throw new Error(`The standalone validator needs ajv runtime helpers: ${requires.join(', ')}. Inline them, or change the schema.`);
    }
    if (/new Function|\beval\(/.test(code)) {
        throw new Error('The standalone validator compiles code at run time.');
    }
    const version = require('ajv/package.json').version;
    return [
        '/* eslint-disable */',
        '// @ts-nocheck',
        `// Generated by scripts/generateSchemaValidator.js from concertino.schema.json with ajv ${version} (standalone). Do not edit.`,
        code,
        '',
    ].join('\n');
}

if (require.main === module) {
    const source = generate();
    if (process.argv.includes('--check')) {
        const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
        if (current !== source) {
            console.error(`${path.relative(process.cwd(), OUT)} is out of date: run npm run generate-validator`);
            process.exit(1);
        }
    } else {
        fs.writeFileSync(OUT, source);
        console.log(`wrote ${path.relative(process.cwd(), OUT)} (${source.length} bytes)`);
    }
}

module.exports = { generate, OUT };
