name: Build

on:
  push:
    branches:
      - main
      - v4.0.0 # Temporary, while we prepare for merge to main
  pull_request:
    branches:
      - main
      - v4.0.0 # Temporary, while we prepare for merge to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Unit Tests

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24.x
          - 22.x
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm test

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: npm-logs
          path: C:\npm\cache\_logs\

      - name: Calculate code coverage
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.os }}
          parallel: true
          fail-on-error: false

  notify:
    needs:
      - build

    name: Code Coverage
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
